name: Deploy Build to Remote Server

on:
  push:
    branches:
      - cicd-pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Set CI Environment Variable
        run: echo 'CI=false' >> $GITHUB_ENV
      - name: Install Dependencies and Build
        run: |
          npm install --force
          npm run build   
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_IP }} >> ~/.ssh/known_hosts    

      - name: Copy Code to Remote Server
        run: scp -r ./build "${{ secrets.SSH_USERNAME }}"@${{ secrets.SSH_IP }}:/var/www/client

  

      
